### ISSUE TITLE
readme with current status

### ISSUE THREAD

**Issue by mdale** [chris838/vp8-ios#1]
could you add a README with current status of this project?

**Comment by chris838** [comment]
I am no longer actively developing this project. It did, however, give me the foundation on which to build a commercial application which uses VP8 video on iOS. So I think it is useful for anyone trying to do the same.

**Comment by pablasso** [comment]
hey @chris838, do you think this same principle could be applied to a webrtc implementation? do you tax the CPU or GPU?

**Comment by chris838** [comment]
Sure I think so. That's something I've wanted to look into.

CPU is heavily utilized - to the point where it's limiting the quality you can achieve. Two possible ways to deal with this would be to offload some processing to the GPU (in particular the color space transforms) or to optimize using ARM SIMD instructions. The Linphone for iPhone application is GPL and opts for the latter, you can take a look at the code here:

git://git.linphone.org/linphone-iphone.git

**Comment by pablasso** [comment]
Thanks a lot for the pointers.

**Comment by daemeh** [comment]
Hi @chris838,

What do you mean by "limiting the quality you can achieve"? Can you share and benchmarks, or at least the FPS for a platform you tested on?

Thanks!

**Comment by chris838** [comment]
I don't really have any benchmarks for this code, sorry! Using the RemoteControlGalileo app (available here: https://github.com/motrr/RemoteControlGalileo) I manage to achieve smooth 10-15 FPS video streaming at around 480x360 - provided I'm using the latest generation of devices (iPad Air, iPad mini 2, iPhone 5/5S etc).
